<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <LangVersion>8</LangVersion>
    <RootNamespace>SadRogue.Primitives.SFML.UnitTests</RootNamespace>
    <!--
    SFML 2.x is broken on .NET 8+; this is the best we can do. As long as nobody tries to build for unsupported
    targets this shouldn't affect anything.
    -->
    <NoWarn>$(NoWarn);NETSDK1206</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="8.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="XUnit.ValueTuples" Version="1.0.1"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TheSadRogue.Primitives.SFML\TheSadRogue.Primitives.SFML.csproj"/>
  </ItemGroup>

  <Import Project="..\TheSadRogue.Primitives.UnitTests.Shared\TheSadRogue.Primitives.UnitTests.Shared.projitems" Label="Shared"/>

</Project>
