<Project Sdk="Microsoft.NET.Sdk">
  <!-- ReSharper disable UnknownProperty -->

  <PropertyGroup>
    <!-- Basic package info -->
    <TargetFrameworks>net5.0;net6.0;net7.0;net8.0;net9.0;netcoreapp3.1;netstandard2.1;net10.0</TargetFrameworks>
    <RootNamespace>SadRogue.Primitives</RootNamespace>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <Version>1.1.3</Version>
    <!-- ReSharper disable once UnknownProperty -->
    <Version Condition="'$(Configuration)'=='Debug'">$(Version)-debug</Version>
    <Authors>Chris3606;Thraka</Authors>
    <Company>TheSadRogue</Company>
    <Copyright>Copyright © 2026 [Christopher Ridley (Chris3606) and TheSadRogue Steve De George JR (Thraka)]</Copyright>
    <Description>A collection of extension methods that allow TheSadRogue.Primitives types to easily interface with MonoGame's equivalents.</Description>

    <!-- More nuget package settings-->
    <PackageId>TheSadRogue.Primitives.MonoGame</PackageId>
    <PackageReleaseNotes>
      - Updated primitives library version targeted
    </PackageReleaseNotes>
    <RepositoryUrl>https://github.com/thesadrogue/TheSadRogue.Primitives</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageTags>2d;grid;primitives;point;rectangle;game;development;standard;monogame;sadrogue;thesadrogue;extensions</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <CheckEolTargetFramework Condition="$(TargetFramework.StartsWith('net5.0')) == true">false</CheckEolTargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <!-- Dependencies -->
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" PrivateAssets="All" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.0.1641" PrivateAssets="All" />
    <PackageReference Include="TheSadRogue.Primitives" Version="1.*" />
  </ItemGroup>

  <!-- When packing, copy the nuget files to the nuget output directory -->
  <Target Name="CopyPackage" AfterTargets="Pack">
    <Copy SourceFiles="$(OutputPath)\$(PackageId).$(Version).nupkg" DestinationFolder="$(OutputPath)..\..\..\nuget" />
    <Copy SourceFiles="$(OutputPath)\$(PackageId).$(Version).snupkg" DestinationFolder="$(OutputPath)..\..\..\nuget" />
  </Target>
</Project>
